// This is free and unencumbered software released into the public domain.
// For more information, please refer to <http://unlicense.org/>

#ifndef OTLS_ONSAG_ONSAGDOC_H_
#define OTLS_ONSAG_ONSAGDOC_H_

#include "wx/docview.h"

/// \par OVERVIEW
///
/// This class is a used when updating the view.
class UpdateHint : public wxObject {
 public:
  /// This enum class contains types of update hints.
  enum class Type {
    kNull,
  };

  /// \brief Default Constructor.
  UpdateHint() {};

  /// \brief Alternate constructor.
  UpdateHint(Type hint) {type_ = hint;};

  /// \brief Sets the hint type.
  /// \param[in] type
  ///   The hint type.
  void set_type(const Type& type) {type_ = type;};

  /// \brief Gets the hint type.
  /// \return The hint type.
  const Type& type() const {return type_;};

 private:
  /// \var type_
  ///   The hint type.
  Type type_;
};


/// \par OVERVIEW
///
/// This is an OnSag application document, which holds all of the information
/// for the project file.
///
/// \par UPDATES
///
/// The document and view need to be updated when the selected analysis sag
/// span is changed. This class does not post any updates by itself, as the
/// document and view updates may take a significant amount of time.
///
/// To update the document, use the RunAnalysis() method. View updates are done
/// with the UpdateAllViews() method. Update hints should be passed along to
/// help the view update properly.
///
/// \par wxWIDGETS LIBRARY BUILD NOTE
///
/// This class requires that the wxWidgets library deviate from the standard
/// build. The wxUSE_STD_IOSTREAM configuration flag must be set to 0, which
/// will force wxWidgets to generate wxInputStream/wxOutputStream classes on the
/// LoadObject() and SaveObject() functions. This is required because this class
/// uses a series of XML handlers to load/save the document, and wxWidgets does
/// not allow std::streams to be used with the XmlDocument::Load() and
/// XmlDocument::Save() functions.
class OnSagDoc : public wxDocument {
 public:
  /// \brief Constructor.
  OnSagDoc();

  /// \brief Destructor.
  ~OnSagDoc();

  /// \brief Loads the document.
  /// \param[in] stream
  ///   The input stream generated by wxWidgets.
  /// \return The input stream.
  wxInputStream& LoadObject(wxInputStream& stream);

  /// \brief Initializes the document.
  /// \param[in] path
  ///   The document filepath.
  /// \param[in] flags
  ///   Document creation flags.
  /// \return If the document is created successfully.
  /// This is called by the wxWidgets framework. All defaults are still being
  /// kept, this function is just being added to and treated as an
  /// initialization constructor.
  virtual bool OnCreate(const wxString& path, long flags);

  /// \brief Saves the document.
  /// \param[out] stream
  ///   The output stream generated by wxWidgets.
  /// \return The output stream.
  wxOutputStream& SaveObject(wxOutputStream& stream);

 private:
  /// \brief This allows wxWidgets to create this class dynamically as part of
  ///   the docview framework.
  wxDECLARE_DYNAMIC_CLASS(OnSagDoc);
};

#endif  // OTLS_ONSAG_ONSAGDOC_H_
